version: '3'

services:
  grafana:  # Descriptive name
    container_name: grafana-container  # Descriptive name
    build:
      context: ./grafana/
    ports:
      - "3000:3000"
    volumes:
      - grafanaetc:/var/lib/grafana
      - grafanadata:/etc/grafana
    restart: always
    user: "1000:1000"
    env_file:
      - ./grafana/.env_grafana  # Check path if needed
    depends_on:
      - database

  database:  # Descriptive name
    container_name: mysql-container  # Descriptive name
    build:
      context: ./db/
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    env_file:
      - ./db/.env_db  # Check path if needed

#  nfdump:
#    container_name: nf-dump
#    build:
#      context: ./nfdump/
#    volumes:
#      - nfdumpdata:/data/nfdump
#    ports:
#      - "2055:2055/udp"
#    command: "nfcapd -T all -l /data/nfdump -p 2055"

  nfexporter:
    container_name: nf-exporter
    build:
      context: ./nfexporter/
    ports:
      - "2000:2000/udp"
    volumes:
      - "./nfexporter/nfexporter.py:/startup/nfexporter.py"
    command: "tail -f /dev/null;"  # Add semicolon

volumes:
  grafanadata:
  grafanaetc:
  dbdata: