version: '3'

services:
  grafana: 
    container_name: grafana-container  
    build:
      context: ./grafana/
    ports:
      - "3000:3000"
    volumes:
      - grafanaetc:/var/lib/grafana
      - grafanadata:/etc/grafana
    restart: always
    user: "1000:1000"
    env_file:
      - ./grafana/.env_grafana 
    depends_on:
      - database

  database: 
    container_name: mysql-container  
    build:
      context: ./db/
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    env_file:
      - ./db/.env_db  

  nfdump:
    container_name: nf-dump
    build:
      context: ./nfdump/
    volumes:
      - nfdumpdata:/data/nfdump
    ports:
      - "2055:2055/udp"

#  nfexporter:
#    container_name: nf-exporter
#    build:
#      context: ./nfexporter/
#    ports:
#      - "2005:2005/udp"
#    volumes:
#      - "./nfexporter/nfexporter.py:/startup/nfexporter.py"
#    command: "tail -f /dev/null;"  

volumes:
  grafanadata:
  grafanaetc:
  dbdata: