{
 "title": "Net-Flow Monitoring",
 "time": { "from": "2024-06-18T18:00:32.978Z", "to": "2024-06-19T00:00:32.978Z" },
 "templating": {
  "list": [
   { "name": "DeviceAddr", "query": "10.100.65.135" }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM tabela_netflow;"
    }
   ]
  },
  {
   "title": "Processing Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT tr AS time,\r\n          ibyt, \r\n          obyt\r\nFROM tabela_netflow\r\nWHERE ra = '$DeviceAddr'"
    }
   ]
  },
  {
   "title": "Top 5 Protocols Throughput",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT pr, SUM(ibyt) AS total_bytes_recebidos, SUM(obyt) AS total_bytes_enviados\r\nFROM tabela_netflow\r\nWHERE pr != '0'\r\nGROUP BY pr\r\nLIMIT 5;"
    }
   ]
  },
  {
   "title": "Top 5 ASN Throughput",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT CONCAT('ASN ', sas) AS sas, SUM(ibyt) AS inbound_bytes, SUM(obyt) AS outbound_bytes\r\nFROM tabela_netflow\r\nGROUP BY sas\r\nORDER BY inbound_bytes + outbound_bytes DESC\r\nLIMIT 5;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    SUM(CASE WHEN `inbound` > 0 THEN 1 ELSE 0 END) AS total_inbound,\r\n    SUM(CASE WHEN `outbound` > 0 THEN 1 ELSE 0 END) AS total_outbound\r\nFROM tabela_netflow;"
    }
   ]
  },
  {
   "title": "Top 10 Source IP Throughput",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT sa, SUM(ibyt) AS total_bytes_recebidos, SUM(obyt) AS total_bytes_enviados\r\nFROM tabela_netflow\r\nWHERE sa != '0.0.0.0'\r\nGROUP BY sa\r\nORDER BY total_bytes_recebidos DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Top 10 Source MAC Throughput",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT ismc, SUM(ibyt) AS total_bytes_recebidos, SUM(obyt) AS total_bytes_enviados\r\nFROM tabela_netflow\r\nWHERE ismc != '00:00:00:00:00:00'\r\nGROUP BY ismc\r\nORDER BY total_bytes_recebidos DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Top 10 Source Port Throughput",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT CONCAT('Port ', CAST(sp AS CHAR)) AS porta, SUM(ibyt) AS total_bytes_recebidos, SUM(obyt) AS total_bytes_enviados\r\nFROM tabela_netflow\r\nWHERE sp != 0\r\nGROUP BY porta\r\nORDER BY total_bytes_recebidos DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Top 10 Destination IP Throughput",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT da, SUM(ibyt) AS total_bytes_recebidos, SUM(obyt) AS total_bytes_enviados\r\nFROM tabela_netflow\r\nWHERE da NOT IN ('0.0.0.0', '255.255.255.255')\r\nGROUP BY da\r\nORDER BY total_bytes_recebidos DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Top 10 Destinantion MAC Throughput",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT idmc, SUM(ibyt) AS total_bytes_recebidos, SUM(obyt) AS total_bytes_enviados\r\nFROM tabela_netflow\r\nWHERE idmc NOT IN ('00:00:00:00:00:00', 'ff:ff:ff:ff:ff:ff')\r\nGROUP BY idmc\r\nORDER BY total_bytes_recebidos DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Top 10 Destination Port Throughput",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT CONCAT('Port ', CAST(dp AS CHAR)) AS porta, SUM(ibyt) AS total_bytes_recebidos, SUM(obyt) AS total_bytes_enviados\r\nFROM tabela_netflow\r\nWHERE dp != 0\r\nGROUP BY porta\r\nORDER BY total_bytes_recebidos DESC\r\nLIMIT 10;"
    }
   ]
  }
 ]
}